# Generated by Django 5.2.4 on 2025-08-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='exchange',
            field=models.CharField(blank=True, choices=[('AMEX', 'American Stock Exchange'), ('ARCA', 'NYSE Arca'), ('BATS', 'BATS Global Markets'), ('NYSE', 'New York Stock Exchange'), ('NASDAQ', 'NASDAQ'), ('NYSEARCA', 'NYSE Arca'), ('OTC', 'Over-the-Counter'), ('CRYPTO', 'Cryptocurrency Exchange')], max_length=20, null=True),
        ),
    ]
