# Generated by Django 5.2.4 on 2025-08-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_asset_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='minute_candle_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
