# Generated by Django 5.2.5 on 2025-08-09 14:37

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asset_search_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asset',
            new_name='idx_asset_sym_cls',
            old_name='core_asset_symbol_7c8ca0_idx',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='idx_asset_status_tradable',
            old_name='core_asset_status_eb1892_idx',
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(django.db.models.functions.text.Lower('symbol'), name='idx_asset_symbol_lower'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['symbol'], name='gin_asset_symbol_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='gin_asset_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
