# Generated by Django 5.2.7 on 2025-10-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_watchlist_is_default_alter_watchlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alpacaaccount',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
