# Generated by Django 5.2.7 on 2025-10-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_sync_status_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='volume',
            field=models.FloatField(),
        ),
    ]
