# Generated by Django 5.2.7 on 2025-12-29 17:31

import django.contrib.postgres.indexes
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_candle_volume"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alpacaaccount",
            options={
                "verbose_name": "Alpaca Account",
                "verbose_name_plural": "Alpaca Accounts",
            },
        ),
        migrations.AlterModelOptions(
            name="asset",
            options={"verbose_name": "Asset", "verbose_name_plural": "Assets"},
        ),
        migrations.AlterModelOptions(
            name="tick",
            options={"verbose_name": "Tick", "verbose_name_plural": "Ticks"},
        ),
        migrations.AlterModelOptions(
            name="watchlist",
            options={
                "verbose_name": "Watch List",
                "verbose_name_plural": "Watch Lists",
            },
        ),
        migrations.AlterModelOptions(
            name="watchlistasset",
            options={
                "verbose_name": "Watch List Asset",
                "verbose_name_plural": "Watch List Assets",
            },
        ),
        migrations.AlterField(
            model_name="alpacaaccount",
            name="api_key",
            field=models.CharField(
                default=" ", help_text="Alpaca API key", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="alpacaaccount",
            name="api_secret",
            field=models.CharField(
                default=" ", help_text="Alpaca API secret", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="alpacaaccount",
            name="name",
            field=models.CharField(
                default="ADMIN",
                help_text="Display name for this account",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="alpacaaccount",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who owns this account",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="alpaca_id",
            field=models.CharField(
                help_text="Alpaca's unique asset identifier",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_class",
            field=models.CharField(
                choices=[
                    ("us_equity", "US Equity"),
                    ("us_option", "US Option"),
                    ("crypto", "Cryptocurrency"),
                ],
                default="us_equity",
                help_text="Asset classification",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="exchange",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AMEX", "American Stock Exchange"),
                    ("ARCA", "NYSE Arca"),
                    ("BATS", "BATS Global Markets"),
                    ("NYSE", "New York Stock Exchange"),
                    ("NASDAQ", "NASDAQ"),
                    ("NYSEARCA", "NYSE Arca"),
                    ("OTC", "Over-the-Counter"),
                    ("CRYPTO", "Cryptocurrency Exchange"),
                ],
                help_text="Trading exchange",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="name",
            field=models.CharField(
                blank=True, help_text="Full asset name", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                help_text="Whether asset is active for trading",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="symbol",
            field=models.CharField(
                db_index=True, help_text="Ticker symbol", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="candle",
            name="close",
            field=models.DecimalField(
                decimal_places=8, help_text="Closing price", max_digits=18
            ),
        ),
        migrations.AlterField(
            model_name="candle",
            name="high",
            field=models.DecimalField(
                decimal_places=8, help_text="Highest price during period", max_digits=18
            ),
        ),
        migrations.AlterField(
            model_name="candle",
            name="low",
            field=models.DecimalField(
                decimal_places=8, help_text="Lowest price during period", max_digits=18
            ),
        ),
        migrations.AlterField(
            model_name="candle",
            name="open",
            field=models.DecimalField(
                decimal_places=8, help_text="Opening price", max_digits=18
            ),
        ),
        migrations.AlterField(
            model_name="candle",
            name="timestamp",
            field=models.DateTimeField(help_text="Start time of the candle period"),
        ),
        migrations.AlterField(
            model_name="candle",
            name="trade_count",
            field=models.IntegerField(
                blank=True,
                help_text="Number of trades during period ('n' field)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="candle",
            name="volume",
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal("0"),
                help_text="Total volume traded (supports crypto fractional volumes)",
                max_digits=24,
            ),
        ),
        migrations.AlterField(
            model_name="candle",
            name="vwap",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Volume-weighted average price ('vw' field)",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="syncstatus",
            name="is_syncing",
            field=models.BooleanField(
                default=False, help_text="Whether a sync is currently in progress"
            ),
        ),
        migrations.AlterField(
            model_name="syncstatus",
            name="last_sync_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of last successful sync", null=True
            ),
        ),
        migrations.AlterField(
            model_name="syncstatus",
            name="sync_type",
            field=models.CharField(
                choices=[("assets", "Assets")],
                default="assets",
                help_text="Type of sync operation",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="syncstatus",
            name="total_items",
            field=models.IntegerField(
                default=0, help_text="Total items synced in last operation"
            ),
        ),
        migrations.AlterField(
            model_name="tick",
            name="alpaca_trade_id",
            field=models.BigIntegerField(
                blank=True, help_text="Alpaca's unique trade ID ('i' field)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="tick",
            name="asset",
            field=models.ForeignKey(
                help_text="Asset this tick is for",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.asset",
            ),
        ),
        migrations.AlterField(
            model_name="tick",
            name="conditions",
            field=models.JSONField(
                blank=True, help_text="Trade conditions ('c' field)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="tick",
            name="exchange_code",
            field=models.CharField(
                blank=True,
                help_text="Exchange code ('x' field)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tick",
            name="price",
            field=models.FloatField(help_text="Trade price ('p' field)"),
        ),
        migrations.AlterField(
            model_name="tick",
            name="size",
            field=models.IntegerField(
                blank=True, help_text="Trade size ('s' field)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="tick",
            name="tape",
            field=models.CharField(
                blank=True,
                help_text="Tape indicator ('z' field)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tick",
            name="timestamp",
            field=models.DateTimeField(help_text="Trade timestamp ('t' field)"),
        ),
        migrations.AlterField(
            model_name="tick",
            name="used",
            field=models.BooleanField(
                default=False,
                help_text="Whether this tick has been aggregated into a candle",
            ),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who owns this watchlist (null for global)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="candle",
            table="core_candle",
        ),
        migrations.CreateModel(
            name="AggregatedCandle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "open",
                    models.DecimalField(
                        decimal_places=8, help_text="Opening price", max_digits=18
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Highest price during period",
                        max_digits=18,
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Lowest price during period",
                        max_digits=18,
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=8, help_text="Closing price", max_digits=18
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        help_text="Total volume traded (supports crypto fractional volumes)",
                        max_digits=24,
                    ),
                ),
                (
                    "trade_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of trades during period ('n' field)",
                        null=True,
                    ),
                ),
                (
                    "vwap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Volume-weighted average price ('vw' field)",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(help_text="Start time of the candle period"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("5T", "5 Minutes"),
                            ("15T", "15 Minutes"),
                            ("30T", "30 Minutes"),
                            ("1H", "1 Hour"),
                            ("4H", "4 Hours"),
                            ("1D", "1 Day"),
                        ],
                        db_index=True,
                        help_text="Aggregation timeframe (5T, 15T, 30T, 1H, 4H, 1D)",
                        max_length=5,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset this candle is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aggregated Candle",
                "verbose_name_plural": "Aggregated Candles",
                "db_table": "core_aggregated_candle",
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["asset", "timeframe", "-timestamp"],
                        name="idx_agg_asset_tf_time_desc",
                    ),
                    django.contrib.postgres.indexes.BrinIndex(
                        fields=["timestamp"], name="brin_agg_timestamp"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("asset", "timeframe", "timestamp"),
                        name="uq_agg_asset_tf_timestamp",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MinuteCandle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "open",
                    models.DecimalField(
                        decimal_places=8, help_text="Opening price", max_digits=18
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Highest price during period",
                        max_digits=18,
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Lowest price during period",
                        max_digits=18,
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=8, help_text="Closing price", max_digits=18
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        help_text="Total volume traded (supports crypto fractional volumes)",
                        max_digits=24,
                    ),
                ),
                (
                    "trade_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of trades during period ('n' field)",
                        null=True,
                    ),
                ),
                (
                    "vwap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Volume-weighted average price ('vw' field)",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(help_text="Start time of the candle period"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset this candle is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Minute Candle",
                "verbose_name_plural": "Minute Candles",
                "db_table": "core_minute_candle",
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["asset", "-timestamp"], name="idx_m1_asset_time_desc"
                    ),
                    django.contrib.postgres.indexes.BrinIndex(
                        fields=["timestamp"], name="brin_m1_timestamp"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("asset", "timestamp"), name="uq_m1_asset_timestamp"
                    )
                ],
            },
        ),
    ]
