# Generated by Django 5.2.11 on 2026-02-21 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_new_candle_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRefreshBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_type', models.CharField(choices=[('minute', '1-Minute Candles'), ('timeframe', 'Timeframe Aggregation'), ('full', 'Full Refresh (1-Min + Timeframes)')], help_text='Type of data refresh operation', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='pending', max_length=20)),
                ('total_assets', models.IntegerField(default=0)),
                ('completed_assets', models.IntegerField(default=0)),
                ('failed_assets', models.IntegerField(default=0)),
                ('data_window_days', models.IntegerField(help_text='Rolling window in days from current date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Refresh Batch',
                'verbose_name_plural': 'Data Refresh Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRefreshTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('candles_fetched', models.IntegerField(default=0)),
                ('timeframes_built', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asset')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.datarefreshbatch')),
            ],
            options={
                'verbose_name': 'Data Refresh Task',
                'verbose_name_plural': 'Data Refresh Tasks',
                'ordering': ['created_at'],
            },
        ),
    ]
