apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alpaca-main.fullname" . }}-nginx-config
  labels:
    {{- include "alpaca-main.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
data:
  default.conf: |
    {{ .Values.nginx.config | nindent 4 }}
