# Generated by Django 5.2.6 on 2025-09-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papertrade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
