name: Build & Push Nginx Image

on:
  # Run on PRs targeting main
  pull_request:
    branches: [main]
    paths:
      - "nginx/**"
      - ".github/workflows/nginx-image.yml"

  # Run automatically when code is pushed/merged to main
  push:
    branches: [main]
    paths:
      - "nginx/**"
      - ".github/workflows/nginx-image.yml"

  # Allow manual runs from the GitHub UI
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # Prevent multiple builds of the same ref running at once
    concurrency:
      group: nginx-image-${{ github.ref }}
      cancel-in-progress: true

    steps:
      # ───────── Git checkout ─────────
      - name: 🛎️  Checkout code
        uses: actions/checkout@v4
        with:
          # full history not needed for docker build
          fetch-depth: 1

      # ───────── Setup Docker Buildx (BuildKit) ─────────
      - name: 🔧 Set up QEMU (multi‑arch)
        uses: docker/setup-qemu-action@v3

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ───────── Login to Docker Hub ─────────
      - name: 🔐 Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ───────── Build & push ─────────
      - name: 🏗️  Build and push nginx image
        uses: docker/build-push-action@v6
        with:
          context: ./nginx # directory to send as build context
          file: ./nginx/Dockerfile.dev # adjust if you rename
          # push images on push/workflow_dispatch, but not on PRs
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            naveedkhan1998/alpaca-nginx:latest
            naveedkhan1998/alpaca-nginx:sha-${{ github.sha }}
          # optional BuildKit cache (makes rebuilds much faster)
          cache-from: type=gha
          cache-to: type=gha,mode=max